### ISSUE TITLE
用Radius认证可以实现么？

### ISSUE THREAD

**Issue by Zenuncl** [yanlookwatchsee/CiscoIPsecVPNSetup#1]
是不是按照这样配置，修改mode_cfg的内容，然后加一个radius的连接在/etc/radius 就好了？

VPN gateway and RADIUS (top)
RADIUS can be used for login validation, IP addresses allocation and accounting. Here is a sample mode_cfg section for /etc/racoon/racoon.conf that enforces RADIUS usage:

mode_cfg {
    pool_size 253;          # IPv4 pool size
    auth_source radius;     # login validated against RADIUS
    conf_source radius;     # IPv4 address obtained by RADIUS
    accounting radius;      # RADIUS accounting
        dns4 10.0.12.1;         # IPv4 DNS server
        wins4 10.0.12.1;        # IPv4 WINS server
        banner "/etc/racoon/motd";  # Banner message for clients
    pfs_group 2;
}
Additionally, you need to create a /etc/radius.conf file that contains the RADIUS server address and the secret shared with the RADIUS server. This file must be owned by root and mode 0600 in order to keep the shared secret secure. Here is an example, see radius.conf(5) for  the details:

auth radius.example.net MyDirtySecret
acct radius.example.net MyDirtySecret

重启racoon是用 service racoon restart 还是直接racoon？还是racooncli？

**Comment by yanlookwatchsee** [comment]
用Radius的话麻烦在安装：默认安装包里不带Radius的code，需要下载带raidus的racoon版本，手动编译。
配置上面，到时和你说的差不多。当然别忘了还要配置Radius server自己。
